### ISSUE TITLE
falsche temperaturanzeige

### ISSUE THREAD

**Issue by MarcusCaepio** [lausser/check_ups_health#2]
Hallo Herr Lausser,
ich nutze Ihr Plugin für die Überwachung unserer APC Galaxy 5500.
Die Webgui und ihr Plugin melden unterschiedliche Temperaturwerte.
Beispiel GUI 27.5, Plugin 25°C
Ich nutze die letzte Version auf der Homepage:
check_ups_health-2.5.2.4.tar.gz
./check_ups_health --hostname $HOSTADDRESS$ --mode battery-health --community $SNMP_COMMUNITY$ --warningx 'battery_temperature'=25 --criticalx 'battery_temperature'=28

Wie behebe ich diesen Unterschied oder wie kann ich die neueste Version Ihres Plugins nutzen?
Im aktuellen Branch ist leider keine ./configure enthalten.

Viele Grüße
MarcusCaepio

**Comment by lausser** [comment]
Hallo Herr Caepio,

hier ist eine ganz neue Version. Wenn check_ups_health andere Werte anzeigt 
als die GUI, kann man nicht viel machen. Das Plugin gibt einfach nur weiter, 
was das Gerät per SNMP geliefert hat.

Grüße,

Gerhard Laußer

Von: MarcusCaepio [mailto:notifications@github.com]
Gesendet: Dienstag, 9. Februar 2016 17:37
An: lausser/check_ups_health check_ups_health@noreply.github.com
Betreff: [check_ups_health] falsche temperaturanzeige (#2)

Hallo Herr Lausser,
ich nutze Ihr Plugin für die Überwachung unserer APC Galaxy 5500.
Die Webgui und ihr Plugin melden unterschiedliche Temperaturwerte.
Beispiel GUI 27.5, Plugin 25°C
Ich nutze die letzte Version auf der Homepage:
check_ups_health-2.5.2.4.tar.gz
./check_ups_health --hostname $HOSTADDRESS$ --mode 
battery-health --community $SNMP_COMMUNITY$ --warningx 
'battery_temperature'=25 --criticalx 'battery_temperature'=28

Wie behebe ich diesen Unterschied oder wie kann ich die neueste Version 
Ihres Plugins nutzen?
Im aktuellen Branch ist leider keine ./configure enthalten.

Viele Grüße
MarcusCaepio

—
Reply to this email directly or view it on GitHub 
https://github.com/lausser/check_ups_health/issues/2 .

**Comment by MarcusCaepio** [comment]
Hallo Herr Lausser,
komischerweise liefert ein anderes plugin, das nur die temp ausließt, den richtigen wert :(
Ist denn Ihre neue Version schon nutzbar? Und wenn ja, wie installiere ich sie?

**Comment by MarcusCaepio** [comment]
Hallo Herr Lausser,
war mein Fehler. Ihr Script holt die Temperatur vom Batteriefühler. Die WebGui hat mir den Wert des externen Fühlers angezeigt. Ich schließe den Issue.
