### ISSUE TITLE
Keine Auswertung von self-tests

### ISSUE THREAD

**Issue by MarcusCaepio** [lausser/check_ups_health#3]
Hallo Herr Lausser,

Ich habe noch ein Problem mit dem hardware-health modus.
Dort bekomme ich leider keine brauchbaren Daten. Ergebnis ist stets:
 ./check_ups_health -v --mode hardware-health --hostname xx --community xx
I am a APC Web/SNMP Management Card (MB:v4.0.1 PF:v5.2.1 PN:apc_hw05_aos_521.bin AF1:v5.1.2 AN1:apc_hw05_chu_512.bin MN:AP9635CH HR:05 SN: ZA1522000018 MD:05/25/2015) (Embedded PowerNet SNMP Agent SW v2.2 compatible)
OK - hardware working fine, at least i hope so, because self-tests were never run
checking hardware and self-tests"

Self-tests werden jedoch ausgeführt:
01/11/2016  17:19:29    UPS: Passed a self-test.
01/11/2016  17:14:17    UPS: Started a self-test.

Könnten Sie mir dabei behiflich sein? Ansonsten wirklich ein super plugin!
Vielen Dank im vorraus

Grüße
MarcusCaepio

Ergänzung: Das Phänomen scheint nur bei APC MGE Galaxy 5500 Modellen aufzutauchen.

**Comment by lausser** [comment]
wenn sie -vvvvvvvvvvvvv ans Plugin dranhängen, sehen sie dann irgendwas bzgl. Selftests? check_ups_health gibt lediglich weiter, was per SNMP vom Gerät geliefert wird.

**Comment by MarcusCaepio** [comment]
Hallo Herr Lausser,
vielen Dank für das Feedback.
Ich glaube, das Problem liegt darin, dass die USV die jeweilige MIB nicht unterstützt.
`PowerNet-MIB::upsBasicIdentModel (1.3.6.1.4.1.318.1.1.1.1.1.1.0.0) : <undef>
PowerNet-MIB::upsBasicIdentModel (1.3.6.1.4.1.318.1.1.1.1.1.1.0) : MGE Galaxy 5500 UPS 60kVA
PowerNet-MIB::upsAdvIdentDateOfManufacture (1.3.6.1.4.1.318.1.1.1.1.2.2.0.0) : <undef>
PowerNet-MIB::upsAdvIdentDateOfManufacture (1.3.6.1.4.1.318.1.1.1.1.2.2.0) : <undef>
PowerNet-MIB::upsAdvIdentSerialNumber (1.3.6.1.4.1.318.1.1.1.1.2.3.0.0) : <undef>
PowerNet-MIB::upsAdvIdentSerialNumber (1.3.6.1.4.1.318.1.1.1.1.2.3.0) :
PowerNet-MIB::upsAdvTestDiagnosticSchedule (1.3.6.1.4.1.318.1.1.1.7.2.1.0.0) : <undef>
PowerNet-MIB::upsAdvTestDiagnosticSchedule (1.3.6.1.4.1.318.1.1.1.7.2.1.0) : <undef>
PowerNet-MIB::upsAdvTestDiagnosticsResults (1.3.6.1.4.1.318.1.1.1.7.2.3.0.0) : <undef>
PowerNet-MIB::upsAdvTestDiagnosticsResults (1.3.6.1.4.1.318.1.1.1.7.2.3.0) : <undef>
PowerNet-MIB::upsAdvTestLastDiagnosticsDate (1.3.6.1.4.1.318.1.1.1.7.2.4.0.0) : <undef>
PowerNet-MIB::upsAdvTestLastDiagnosticsDate (1.3.6.1.4.1.318.1.1.1.7.2.4.0) : <undef>
`
Werde mich diesbezüglich an den Hersteller wenden und den Issue schließen.
Schönes Wochenende! :)
